### ISSUE TITLE
Set up kamban board

### ISSUE THREAD

**Issue by chiztechnology** [Svartstein/catalog-of-my-things#34]
### Hello dear reviewer! 👋 
We just created this issue in answer to the requirements about setting up the kanban board for the Ruby group project

Kindly find the link to [our group project](https://github.com/Swarzstein/catalog-of-my-things/projects/1)
We're going to work in group of 2 in this project.
@Swarzstein  (Juan ZORRILA as Person #1) and
@chiztechnology (CHIZUNGU ISRAEL as Person #2).

Best regards

**Comment by 1GORDON** [comment]
##
## Hi @chiztechnology & @Swarzstein ✋

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] Kindly ensure the `Add visible methods in the diagram` card is assigned to a team member.
![kanban1](https://user-images.githubusercontent.com/63917725/229635333-fff84847-4eb0-4aed-a977-6c57e35f87b1.PNG)

- [ ] Kindly ensure the `Create game and author table` card has the number of points in the [Xpt] prefix.
![Kanban2](https://user-images.githubusercontent.com/63917725/229635651-33733651-ad8e-477f-b143-71c0e006c716.PNG)

- [ ] You seem to have used the same title for different cards, i.e `Implement Main functions` card for group tasks. Kindly use different titles for these cards since they represent different tasks otherwise it will appear like a repetition.
![kanban3](https://user-images.githubusercontent.com/63917725/229636280-e8c0156b-a520-4d64-9cbe-7cdda9ac6c13.PNG)
![kanban4](https://user-images.githubusercontent.com/63917725/229636301-b67af12f-6d95-4931-a6c4-ac171aad88a8.PNG)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by chiztechnology** [comment]
Tanks for your great support.
We will work accordingly and apply the changes.

Thanks & Regards

**Comment by chiztechnology** [comment]
We successfully applied the requested changes.
thanks, a lot dear @1GORDON .
We request another review then.

Best regards

**Comment by Owusu-Desmond** [comment]
Hi @Swarzstein  and @chiztechnology , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
📌 Good to assign tasks to team members  ✅
📌 Descriptive card titles✅
📌 Great working on the setup of the project board ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
